### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by caraar12345** [caraar12345/otterbot#1]
- [ ] Live stock prices
- [ ] Set up the CD pipeline to have different functions for different slash commands
  - [ ] _Maybe it's time to set up a microservice K8s cluster - `service.otterbot`?!_

**Comment by caraar12345** [comment]
Changed to GitHub Projects.
